### PR TITLE
Adding support for native backstack instead of maintaining a custom back

### PR DESCRIPTION
**Pull request by sunnygoyal**
> Also fixing motion events not working in Android-13 device mirroring
> Minor fixes for view capture parsing

### CODE REVIEW

**Comment by sandonian** [comment]
How come you are using backstack.js rather than the native History API? https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by sunnygoyal** [comment]
> How come you are using backstack.js rather than the native History API? https://developer.mozilla.org/en-US/docs/Web/API/History_API

backstack.js is using the web-history api

**Comment by sandonian** [comment]
> > How come you are using backstack.js rather than the native History API? https://developer.mozilla.org/en-US/docs/Web/API/History_API
> 
> backstack.js is using the web-history api

Still, which features are we using from it that make the additional wrapper worthwhile? The description reads, "Javascript/jQuery library to provide a usable mobile-like user-experience for web. Create x number of tabs with their own backstacks of pages to allow users to navigate your web app in a mobile-app-like manner.", 

but this change only seems to be limited to backstack functionality. Is it easier to implement using backstack js than using the History API?

**Comment by sunnygoyal** [comment]
I think the name might be causing the confusion. This is a completely in-house implementation. back_stack.js just happens to be the javascript file name where the code is written

**Comment by sandonian** [comment]
> I think the name might be causing the confusion. This is a completely in-house implementation. back_stack.js just happens to be the javascript file name where the code is written

Oh! haha, that makes sense. I was looking at https://github.com/gregorymarkthomas/backstackjs. Pardon my confusion.

**Comment by sandonian** [comment]
Approved.

**Pull request merged**
